{{- if .Values.postgresql.persistence.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: {{ .Values.global.namespace }}
  labels:
    type: local
    app: postgresql
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.postgresql.persistence.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/postgresql"
    type: DirectoryOrCreate
{{- end }}
