{{- if .Values.django.migrations.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrations
  namespace: {{ .Values.global.namespace }}
spec:
  backoffLimit: {{ .Values.django.migrations.backoffLimit }}
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "{{ .Values.vault.role }}"
        vault.hashicorp.com/agent-inject-status: "update"
        
        vault.hashicorp.com/agent-inject-secret-django-config: "secret/data/django-app/django"
        vault.hashicorp.com/agent-inject-template-django-config: |
          {{`{{- with secret "secret/data/django-app/django" -}}
          export SECRET_KEY='{{ .Data.data.secret_key }}'
          export DEBUG='{{ .Data.data.debug }}'
          {{- end -}}`}}
        
        vault.hashicorp.com/agent-inject-secret-postgres-config: "secret/data/django-app/postgres"
        vault.hashicorp.com/agent-inject-template-postgres-config: |
          {{`{{- with secret "secret/data/django-app/postgres" -}}
          export DB_NAME='{{ .Data.data.database }}'
          export DB_USER='{{ .Data.data.username }}'
          export DB_PASSWORD='{{ .Data.data.password }}'
          {{- end -}}`}}
    spec:
      serviceAccountName: django-app-sa
      containers:
      - name: migrations
        image: {{ .Values.django.image.repository }}:{{ .Values.django.image.tag }}
        command:
        - /bin/sh
        - -c
        - |
          # Ждем секреты
          while [ ! -f /vault/secrets/django-config ] || [ ! -f /vault/secrets/postgres-config ]; do
            sleep 2
          done
          
          # Загружаем секреты
          . /vault/secrets/django-config
          . /vault/secrets/postgres-config
          
          # Проверяем
          echo "Using database: $DB_NAME with user: $DB_USER"
          
          # Выполняем миграции
          python manage.py migrate --no-input
          echo "Creating superuser..."
          echo "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.filter(username='admin').exists() or User.objects.create_superuser('admin', 'admin@example.com', 'admin')" | python manage.py shell
      restartPolicy: Never
{{- end }}
